#!/bin/bash
#SBATCH -t 4:00:00                 # wall time
#SBATCH --ntasks-per-node=8        # tasks per node
#SBATCH --exclusive                # exclusive node access
#SBATCH --mem=0                    # all mem avail
#SBATCH --mail-type=FAIL           # only send email on failure
#SBATCH --overcommit               # Needed for pytorch
#SBATCH -p batch
#SBATCH -N 4                       # number of nodes
#SBATCH -A 	convai_convaird_nemo-speech
#SBATCH -J 	convai_convaird_nemo-speech-sample:cer_ssim_annotation

source containers_magpie.sh
export HYDRA_FULL_ERROR=1

set -x

CUTS_DIR="/data/speech_data/en/jhsdGtc20Amp20Keynote/lhotse_shar_shuffle_shardSize256/cuts_with_ipa"
TARGET_AUDIO_DIR="/data/speech_data/en/jhsdGtc20Amp20Keynote/lhotse_shar_shuffle_shardSize256/target_audio"
CONTEXT_AUDIO_DIR="/data/speech_data/en/jhsdGtc20Amp20Keynote/lhotse_shar_shuffle_shardSize256/context_audio"
OUTPUT_DIR="/data/speech_data/en/jhsdGtc20Amp20Keynote/lhotse_shar_shuffle_shardSize256/cuts_with_ipa_cer_ssimOpus"
CODE_DIR="/gitrepos/NeMo"
BATCH_SIZE=16
LOG_LEVEL="INFO"

EXP_DIR="/lustre/fsw/llmservice_nemo_speechlm/users/pneekhara/gitrepos/Experiments2026/CER_SSIM_Annotation"
mkdir -p $EXP_DIR

read -r -d '' cmd <<EOF
echo "*******STARTING CER/SSIM ANNOTATION********" \
&& export HF_HOME="/gitrepos/huggingface" \
&& cd ${CODE_DIR} ; export PYTHONPATH="${CODE_DIR}:${PYTHONPATH}" \
&& python -u ${CODE_DIR}/scripts/magpietts/annotate_lhotse_shards_with_cer_ssim.py \
    --cuts-dir ${CUTS_DIR} \
    --target-audio-dir ${TARGET_AUDIO_DIR} \
    --context-audio-dir ${CONTEXT_AUDIO_DIR} \
    --output-dir ${OUTPUT_DIR} \
    --batch-size ${BATCH_SIZE} \
    --log-level ${LOG_LEVEL}
EOF

echo $cmd

bash -c "${cmd}"
# srun -o ${EXP_DIR}/slurm-cer-ssim-%j-%n.out -e ${EXP_DIR}/slurm-cer-ssim-%j-%n.err --no-container-mount-home --container-image="$CONTAINER" $MOUNTS bash -c "${cmd}"
set +x
