dataset:
  _target_: "nemo.collections.tts.torch.data.TTSDataset"
  manifest_filepath: ${train_dataset}
  sample_rate: ${sample_rate}
  text_tokenizer:
    _target_: nemo.collections.tts.torch.tts_tokenizers.EnglishCharsTokenizer
  sup_data_types: ["ssl_features"]
  max_duration: 2
  ssl_features_folder: ???
dataloader_params:
  drop_last: false
  shuffle: false
  batch_size: 8
  num_workers: 1
  pin_memory: true
